calisphere/urls.py
from django.urls import re_path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.conf import settings
from calisphere.home import HomeView
from . import views
from . import collection_views
from . import institution_views

app_name = 'calisphere'

urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
    re_path(r'^select-index/(?P<index>.*)/', views.select_index, name='select_index'),
    re_path(r'^search/$', views.search, name='search'),
    re_path(r'^item/(?P<item_id>.*)/$', views.item_view, name='itemView'),
    re_path(r'^collections/$',
        collection_views.collections_directory,
        name='collectionsDirectory'),
    re_path(r'^collections/(?P<collection_letter>[a-zA-Z]{1})/$',
        collection_views.collections_az,
        name='collectionsAZ'),
    re_path(r'^collections/(?P<collection_letter>num)/$',
        collection_views.collections_az,
        name='collectionsAZ'),
    re_path(r'^collections/(?P<collection_id>\d*)/$',
        collection_views.collection_search,
        name='collectionView'),
    re_path(r'^collections/(?P<collection_id>\d*)/reports/(?P<facet>[^/].*)/(?P<facet_value>.*)/$',
        views.report_collection_facet_value,
        name='reportCollectionFacetValue'),
    re_path(r'^collections/(?P<collection_id>\d*)/reports/(?P<facet>.*)/$',
        views.report_collection_facet,
        name='reportCollectionFacet'),
    re_path(r'^collections/(?P<collection_id>\d*)/(?P<cluster>[^/].*)/(?P<cluster_value>.*)/$',
        collection_views.collection_facet_value,
        name='collectionFacetValue'),
    re_path(r'^collections/(?P<collection_id>\d*)/(?P<facet>.*)/$',
        collection_views.collection_facet,
        name='collectionFacet'),
    re_path(r'^collections/(?P<collection_id>\d*)/(?P<facet>.*).json$',
        collection_views.collection_facet_json,
        name='collectionFacetJson'),

    # Redirects to new 'exhibitions'
    re_path(r'^collections/themed/$',
        RedirectView.as_view(url='/exhibitions/'),
        name='themedCollections'),
    re_path(r'^collections/cal-cultures/$',
        RedirectView.as_view(url='/cal-cultures/'),
        name='calCultures'),
    re_path(r'^collections/jarda/$',
        RedirectView.as_view(url='/exhibitions/t11/jarda/'),
        name='jarda'),
    re_path(r'^collections/titleSearch/$',
        collection_views.collections_search,
        name='collectionsTitleSearch'),
    re_path(r'^collections/titles.json$',
        collection_views.collections_titles,
        name='collectionsTitleData'),

    re_path(r'^institution/(?P<repository_id>\d*)/$',
        institution_views.repository_collections,
        name='repositoryCollections'),
    re_path(r'^institution/(?P<repository_id>\d*)/collections/$',
        institution_views.repository_collections,
        name='repositoryCollections'),
    re_path(r'^institution/(?P<repository_id>\d*)/items/$',
        institution_views.repository_search,
        name='repositorySearch'),

    re_path(r'^(?P<campus_slug>UC\w{1,2})/$',
        institution_views.campus_collections,
        name='campusCollections'),
    re_path(r'^(?P<campus_slug>UC\w{1,2})/collections/$',
        institution_views.campus_collections,
        name='campusCollections'),
    re_path(r'^(?P<campus_slug>UC\w{1,2})/items/$',
        institution_views.campus_search,
        name='campusSearch'),
    re_path(r'^(?P<campus_slug>UC\w{1,2})/institutions/$',
        institution_views.campus_institutions,
        name='campusInstitutions'),

    re_path(r'^institutions/$', institution_views.campus_directory, name='campusDirectory'),
    re_path(r'^institutions/statewide-partners/$',
        institution_views.statewide_directory,
        name='statewideDirectory'),
    re_path(r'about/$',
        TemplateView.as_view(template_name='calisphere/about.html'),
        name='about'),
    re_path(r'help/$',
        TemplateView.as_view(template_name='calisphere/help.html'),
        name='help'),
    re_path(r'terms/$',
        TemplateView.as_view(template_name='calisphere/termsOfUse.html'),
        name='termsOfUse'),
    re_path(r'privacy/$',
        TemplateView.as_view(template_name='calisphere/privacyStatement.html'),
        name='privacyStatement'),
    re_path(r'outreach/$',
        TemplateView.as_view(template_name='calisphere/outreach.html'),
        name='outreach'),
    re_path(r'contribute/$',
        TemplateView.as_view(template_name='calisphere/contribute.html'),
        name='contribute'),
    re_path(r'jobs/$',
        TemplateView.as_view(template_name='calisphere/jobs.html'),
        name='jobs'),
    re_path(r'overview/$', 
        TemplateView.as_view(template_name='calisphere/overview.html'),
        name='overview'),
    re_path(r'posters/$', views.posters, name='posters'),
    re_path(r'sitemap-(?P<section>.*).xml$', views.sitemap_section),
    re_path(r'sitemap-(?P<section>.*).xml.gz$', views.sitemap_section_zipped),

    # AJAX HELPERS
    re_path(r'^relatedCollections/',
        views.related_collections,
        name='relatedCollections'),
    re_path(r'^relatedExhibitions',
        views.related_exhibitions,
        name='relatedExhibitions'),
    re_path(r'^carousel/', views.item_view_carousel, name='carousel'),
    re_path(r'^contactOwner/', views.contact_owner, name='contactOwner'),
]

if settings.UCLDC_METADATA_SUMMARY:
    urlpatterns.insert(0,
        re_path(r'^collections/(?P<collection_id>\d*)/metadata/$',
            collection_views.collection_metadata,
            name='collectionMetadata'),
    )
    urlpatterns.insert(0,
        re_path(r'^collections/(?P<collection_id>\d*)/browse/$',
            collection_views.collection_browse,
            name='collectionBrowse'),)

calisphere/templates/calisphere/campusDirectory.html
{% extends "calisphere/base.html" %}
{% load calisphere-extras %}
{% load static %}

{% block page-metadata %}
{% include "calisphere/microdata.html" with title='UC Partners' %}
{% endblock %}

{% block content %}

{% include "calisphere/institutionsHeader.html" %}

<div class="inst-textboxes">
{% for campus in campuses %}
	<div class="inst-textboxes__box">
		<h2 class="inst-textboxes__box-heading">
      <a href="{% url 'calisphere:campusCollections' campus.slug %}">{{ campus.name }}</a>
    </h2>
		<ul class="inst-textboxes__list">
  {% for repository in repositories %}
    {% if repository.campus == campus.name %}
      <li class="inst-textboxes__list-item">
        <a class="inst-textboxes__link" href="{% url 'calisphere:repositoryCollections' repository.repository_id %}">
          {{ repository.name }}
        </a>
      </li>
    {% endif %}
  {% endfor %}
  	</ul>
  </div>
{% endfor %}
</div>

{% endblock %}

calisphere/templates/calisphere/carousel.html
{% load calisphere-extras %}
{% load static %}
  {% for carousel_item in search_results %}
  <div class="js-carousel_item {% if carousel_item.id == item_id %}carousel__item--selected{% else %}carousel__item{% endif %}">
    <a class="carousel__link js-item-link" href="{% url 'calisphere:itemView' carousel_item.id %}" data-item_id="{{ carousel_item.id }}" data-item_number="{{ start|add:forloop.counter0 }}">
      <div class="thumbnail__container">
        {% if 'reference_image_md5' in carousel_item %}
          <img
          data-lazy="{{ thumbnailUrl }}crop/120x120/{{ carousel_item.reference_image_md5 }}"
          {% if carousel_item.id == item_id %}
          class="carousel__image--selected"
          {% else %}
          class="carousel__image"
          {% endif %}
          alt="{{ carousel_item.title.0|truncatewords:12 }}"
          >

          {% if carousel_item.type_ss.0|lower == "moving image" %}
          <span class="carousel__overlay-icon fa-play-circle-o"></span>
          {% elif carousel_item.type_ss.0|lower == "sound"%}
          <span class="carousel__overlay-icon fa-volume-up"></span>
          {# elif carousel_item.type_ss.0|lower == "text"#}
          <!-- <span class="carousel__overlay-icon fa-file-text-o"></span> -->
          {% elif carousel_item.type_ss.0|lower == "dataset" %}
          <span class="carousel__overlay-icon fa-bar-chart"></span>
          {% endif %}

        {% else %}
          {% if carousel_item.type_ss.0|lower == "moving image" %}
          <span class="carousel__tile-icon fa-play-circle-o"></span>
          {% elif carousel_item.type_ss.0|lower == "sound"%}
          <span class="carousel__tile-icon fa-volume-up"></span>
          {% elif carousel_item.type_ss.0|lower == "text"%}
          <span class="carousel__tile-icon fa-file-text-o"></span>
          {% elif carousel_item.type_ss.0|lower == "dataset" %}
          <span class="carousel__tile-icon fa-bar-chart"></span>
          {% else %}
          <span class="carousel__tile-icon fa-file"></span>
          {% endif %}
        {% endif %}
      </div>
      <div class="carousel__thumbnail-caption">{{ start|add:forloop.counter0 }}: {{ carousel_item.title.0|truncatewords:12 }}
      </div>
    </a>
  </div>
  {% endfor %}

calisphere/templates/calisphere/collectionsTitleSearch.html
{% extends "calisphere/collectionsDirectory.html,calisphere/pjaxTemplates/collectionsDirectory.html"|pjax:request %}

{% load calisphere-extras %}
{% load staticfiles %}

{% block page-metadata %}
{% include "calisphere/microdata.html" with title='Collections Title Search' meta_robots="noindex,follow" %}
{% endblock %}

{% block collectionContent %}
<style>

.typeahead,
.tt-query,
.tt-hint {
  width: 100%;
  border: 2px solid #ccc;
  -webkit-border-radius: 8px;
     -moz-border-radius: 8px;
          border-radius: 8px;
  outline: none;
}

.typeahead {
  background-color: #fff;
}

.typeahead:focus {
  border: 2px solid #0097cf;
}

.tt-query {
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
     -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}

.tt-menu {
  width: 100%;
  margin: 32px 0;
  padding: 8px 0;
  background-color: #fff;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.2);
  -webkit-border-radius: 8px;
     -moz-border-radius: 8px;
          border-radius: 8px;
  -webkit-box-shadow: 0 5px 10px rgba(0,0,0,.2);
     -moz-box-shadow: 0 5px 10px rgba(0,0,0,.2);
          box-shadow: 0 5px 10px rgba(0,0,0,.2);
}

.tt-suggestion {
  padding: 3px 20px;
  /* font-size: 18px;
  line-height: 24px; */
}

.tt-suggestion:hover {
  cursor: pointer;
  color: #fff;
  background-color: #0097cf;
}

.tt-suggestion.tt-cursor {
  color: #fff;
  background-color: #0097cf;

}

.tt-suggestion p {
  margin: 0;
}

.twitter-typeahead {
  width: 100%;
  display: block !important;
}

</style>

<div class="titlesearch">

        <form class="titlesearch__form" role="search" onsubmit="false()">
          <label for="titlesearch__field" class="sr-only">Search for keywords within the titles of Calisphere's collections</label>
          <div class="input-group">
<input id="titlesearch__field" type="search" placeholder="Search for keywords within the titles of Calisphere's collections" class="form-control">
            <span class="input-group-btn">
              <button class="btn btn-default global-search__button" type="submit" aria-label="search"><span class="fa fa-search"></span>
              </button>
            </span>
          </div>
        </form>
      </div>

{% endblock %}

calisphere/templates/calisphere/component-metadata-dd.html
{% load calisphere-extras %}
<dd class="meta-block__defin">
{% if value|is_string %}
{{ value|urlize }}
{% else %}
{% for v in value %}
  {% if v.text %}
    {{ v.text|urlize }}
  {% else %}
    {{ v|urlize }}
  {% endif %} <br> {% endfor %}
{% endif %}
</dd>

calisphere/templates/calisphere/institutionViewInstitutions.html
{% extends "calisphere/institutionView.html" %}
{% load calisphere-extras %}
{% load static %}

{% block page-metadata %}
{% include "calisphere/microdata.html" with description=institution.description %}
{% endblock %}

{% block sidebar %}

  <div class="row">
    
    {% with "institutions" as mode %}
      {% include "calisphere/institutionViewSidebar.html" %}
    {% endwith %}

    <div class="col-sm-6 col-md-12">

      <!-- Begin Search Within Field -->
      <!-- <div class="search-collection">
        <form id="js-searchInstitution" action="{% url 'calisphere:campusSearch' campus_slug %}" method="get">
          <label for="search-collection__field" class="search-collection__label">Search {% if repository_id and uc_institution %}{{ uc_institution.0.name }}, {% endif %}{{ institution.name }}</label>
          <div class="input-group">
            <input id="search-collection__field" type="search" name="rq" class="form-control search-collection__field" form="js-facet">
            <span class="input-group-btn">
              <button class="btn btn-default search-collection__button" type="submit" form="js-facet">Search
              </button>
            </span>
          </div>
        </form>
      </div>       -->
      <!-- End Search Within Field -->
      
    </div>

  </div>
  
{% endblock %}

{% block filters %}{% endblock %}

{% block mainContent %}
  <h2 class="text__institution-heading2">Contributors at {{ institution.name }}</h2>
  

  <!-- Begin Institution List Component -->

  <div class="inst-contrib">

    <ul class="inst-contrib__list">
      {% for institution in institutions %}
          <li class="inst-contrib__list-item"><a href="{% url 'calisphere:repositoryCollections' institution.id %}">{{ institution.name }}</a></li>
      {% endfor %}
    </ul>

  </div>

  <!-- End Institution List Component -->
{% endblock %}
  
{% block footerScripts %}
  <script>
    $(document).ready(function() {
      $(document).on('focus', '.js-institutionSearch', function() {
        $('#js-searchInstitution').submit();
      });
    });
  </script>
{% endblock %}

calisphere/templates/calisphere/institutionsHeader.html
<h1>Institutions Contributing to Calisphere</h1>

<div class="inst-intro">
  <div class="row">
    <div class="col-xs-12 col-sm-6 institutions-intro__overview">
      <p>All of the items in Calisphere have been contributed by educational and cultural heritage institutions in California. Use the tabs below to explore the rich digital collections of the ten University of California campuses and our partners statewide.</p>
      <p class="institutions-intro__text">Learn more <a href="/overview/">about the collections in Calisphere</a>, including: how primary source records are described; how shared community values and standards guide access to historical materials; how we strive  to provide responsible access to digital primary sources--and how you can help!</p>
    </div>
    <div class="col-xs-12 col-sm-6 institutions-intro__description">
      
    </div>
  </div>

  <!-- Add 'button__secondary' class to <a> element below for active state -->

  <div class="row">
    <div class="col-xs-6 col-sm-3 institutions-intro__button-uc">
      <a class="btn btn-default btn-block {% if campuses %}button__secondary{% endif %}" 
      href="{% url 'calisphere:campusDirectory' %}">UC Partners</a>
    </div>
    <div class="col-xs-6 col-sm-3 institutions-intro__button-state">
      <a class="btn btn-default btn-block {% if state_repositories %}button__secondary{% endif %}" 
      href="{% url 'calisphere:statewideDirectory' %}">Statewide Partners</a>
    </div>
  </div>

</div>

calisphere/templates/calisphere/item.html
{% load calisphere-extras %}

<nav class="breadcrumb--style2" aria-label="breadcrumb navigation">
  <ul>
  {% if item.parsed_repository_data %}
    <li>
      <a href="{% url 'calisphere:repositoryCollections' item.parsed_repository_data.0.id %}">
      {% if item.parsed_repository_data.0.campus %}{{ item.parsed_repository_data.0.campus }}, {% endif %}
      {{ item.parsed_repository_data.0.name }}
      </a>
    </li>
  {% endif %}

  {% if item.parsed_collection_data %}
    <li>
      <a href="{% url 'calisphere:collectionView' item.parsed_collection_data.0.id %}" class="js-relatedCollection">{{ item.parsed_collection_data.0.name }}</a>
    </li>
  {% endif %}
    <li>{{ item.title.0 }}</li>
  </ul>
</nav>

<h1 class="obj__heading">
  {% if item.harvest_type == 'hosted' %}
    {% if item.multiFormat %}Multi-format{% else %}{{ item.type.0|title }}{% endif %}{% if 'structMap' in item %} set{% else %}{% endif %}
  {% else %}
    {{ item.type.0|title }}
  {% endif %}
 / <strong>{{ item.title.0|truncatewords:12 }}</strong></h1>

<div id="js-objectViewport" data-item_id="{{item.id}}">
{% if item.harvest_type == 'hosted' and 'structMap' in item %}
  {% include 'calisphere/objectViewer/complex-object.html' %}
{% elif item.harvest_type == 'hosted' and item.contentFile.format == 'image' %}
  {% include 'calisphere/objectViewer/hosted-simple-image.html' %}
{% elif item.harvest_type == 'hosted' and item.contentFile.format == 'video' %}
  {% include 'calisphere/objectViewer/hosted-simple-video.html' %}
{% elif item.harvest_type == 'hosted' and item.contentFile.format == 'audio' %}
  {% include 'calisphere/objectViewer/hosted-simple-audio.html' %}
{% elif item.harvest_type == 'hosted' and item.contentFile.format == 'file' %}
  {% include 'calisphere/objectViewer/hosted-simple-file.html' %}
{% else %}
  {% include 'calisphere/objectViewer/object-tiles-and-overlays.html' %}
{% endif %}
</div>

{% include "calisphere/itemButtons.html" %}

<h2 class="meta-heading">
  {% if item.harvest_type == 'harvested' %}
    Item information.
    {% if item.oac == False %}
    <a class="meta-heading__preview-link" href="{{ item.url_item }}">
      View source record on contributor's website.
    </a>
    {% endif %}
  {% elif item.harvest_type == 'hosted' %}
    {% if 'structMap' in item and 'selected' in item and item.selected == True %}
      Summary information.
    {% elif 'structMap' in item %}
      Item information. <a href="{% url 'calisphere:itemView' item.id %}" class="js-set-link">Go to summary information.</a>
    {% else %}
      Item information.
    {% endif %}
  {% endif %}
</h2>

<div class="row">
  <div class="col-md-8">
    {% if 'selected' in item and item.selected == False %}
      {% include "calisphere/component-metadata.html" %}
    {% else %}
      {% include "calisphere/item-metadata.html" %}
    {% endif %}
  </div>
  <div class="col-md-4">
    <div class="meta-sidebar">
      <div class="meta-sidebar__block">
        <h3>About the collections in Calisphere</h3>
        <p>Learn more about the collections in Calisphere. View our <a href="/overview/">statement on digital primary resources</a>.</p>
      </div>
      <div class="meta-sidebar__block">
        <h3>Copyright, permissions, and use</h3>
        <p>If you're wondering about permissions and what you can do with this item, a good starting point is the "rights information" on this page. See our <a href="/terms/">terms of use</a> for more tips.</p>
      </div>
      <div class="meta-sidebar__block">
        <h3>Share your story</h3>
        <p>Has Calisphere helped you advance your research, complete a project, or find something meaningful? We'd love to hear about it; please <a href="/contact/">send us a message</a>.</p>
      </div>
    </div>
  </div>
</div>

{% if item.parsed_collection_data.0.disqus_shortname %}
<div class="comment">
  <div id="disqus_loader" class="comment_clickthrough" data-disqus="{{ item.parsed_collection_data.0.disqus_shortname }}">
    <div class="comment__text">
      <h2>New! This item supports comments!</h2>
      <p>We are testing a commenting feature on this item. <button class="button__link js-disqus">Load comments</button>.</p>
    </div>
    <button class="comment__link js-disqus">Join The <br>Discussion</button>
  </div>

  <div class="comment__thread">
    <div id="disqus_thread"></div>
  </div>
</div>
{% endif %}

calisphere/templates/calisphere/jobs.html
{% extends "calisphere/base.html" %}

{% block page-metadata %}
{% include "calisphere/microdata.html" with title='Jobs' description='The California Digital Library is seeking an energetic, media-savvy individual to help us develop a social media strategy for Calisphere. This is a unique, short-term opportunity.'%}
{% endblock %}

{% block content %}

<h1>Job Opportunities</h1>

<!-- Begin Static About Component -->

<div class="static">

  <div class="col-sm-8 static__main">

		<p>There are no open positions at this time. Please check back later!</p>
  </div>

  <div class="col-sm-4 static__sidebar">

  	<h2 class="static__sidebar-heading">Looking for more jobs in digital libraries?</h2>

  	<p>Calisphere is managed by the California Digital Library (CDL) at the University of California Office of the President (UCOP). Other employment and internship opportunities at our organization are listed on the <a href="http://www.cdlib.org/about/jobs.html">CDL website</a> and on the <a href="https://jobs.ucop.edu/">UCOP employment website.</a></p>


  </div>

</div>

<!-- End Static About Component -->
{{ q }}
{% endblock %}

calisphere/templates/calisphere/list-results.html
{% load static %}
<div class="listview">
{% for item in search_results %}
  <div class="row listview__container">
    <div class="col-xs-3">
      <a class="list-view__thumbnail__container js-item-link" href="{% url 'calisphere:itemView' item.id %}" data-item_id="{{ item.id }}" data-item_number="{{ search_form.start|add:forloop.counter0 }}">
        {% if 'reference_image_md5' in item %}
          <img class="thumbnail__image"
          src="{{ thumbnailUrl }}crop/210x210/{{ item.reference_image_md5 }}"
          srcset="{{ thumbnailUrl }}crop/210x210/{{ item.reference_image_md5 }} 60w, {{ thumbnailUrl }}crop/310x310/{{ item.reference_image_md5 }} 50w"
          sizes="100vw"
          alt="{{ item.title.0|truncatewords:12 }}">

          {% if item.type_ss.0|lower == "moving image" %}
          <div class="listview__overlay-icon fa-play-circle-o"></div>
          {% elif item.type_ss.0|lower == "sound"%}
          <div class="listview__overlay-icon fa-volume-up"></div>
          {# elif item.type_ss.0|lower == "text"#}
          <!-- <div class="listview__overlay-icon fa-file-text-o"></div> -->
          {% elif item.type_ss.0|lower == "dataset" %}
          <div class="listview__overlay-icon fa-bar-chart"></div>
          {% endif %}

        {% else %}
          {% if item.type_ss.0|lower == "moving image" %}
          <div class="listview__tile-icon fa-play-circle-o"></div>
          {% elif item.type_ss.0|lower == "sound"%}
          <div class="listview__tile-icon fa-volume-up"></div>
          {% elif item.type_ss.0|lower == "text"%}
          <div class="listview__tile-icon fa-file-text-o"></div>
          {% elif item.type_ss.0|lower == "dataset" %}
          <div class="listview__tile-icon fa-bar-chart"></div>
          {% elif item.type_ss.0|lower == "image" %}
          <div class="listview__tile-icon fa-picture-o"></div>
          {% else %}
          <div class="listview__tile-icon fa-file"></div>
          {% endif %}
        {% endif %}
      </a>
    </div>
    <div class="col-xs-9">
      <div class="listview__metadata">
        <dl class="meta-inline__list">
          <dt class="meta-inline__type">Title</dt>
          <dd class="meta-inline__defin">
            <a class="listview__link js-item-link" href="{% url 'calisphere:itemView' item.id %}"
            data-item_id="{{ item.id }}" data-item_number="{{ search_form.start|add:forloop.counter0 }}">
              {{ item.title.0 }}
            </a>
          </dd>

          {% if 'creator' in item %}
          <dt class="meta-inline__type">Creator/Contributor</dt>
          <dd class="meta-inline__defin">{{ item.creator.0 }}</dd>
          {% endif %}

          {% if 'date' in item %}
          <dt class="meta-inline__type">Date Created and/or Issued</dt>
          <dd class="meta-inline__defin">{{ item.date.0 }}</dd>
          {% endif %}

          {% if 'description' in item %}
          <dt class="meta-inline__type">Description</dt>
          <dd class="meta-inline__defin">{{ item.description.0 }}</dd>
          {% endif %}

          {% if 'subject' in item %}
          <dt class="meta-inline__type">Subject</dt>
          <dd class="meta-inline__defin">{{ item.subject.0 }}</dd>
          {% endif %}

          {% if 'repository_name' in item %}
          <dt class="meta-inline__type">Contributing Institution</dt>
          <dd class="meta-inline__defin">{% if 'campus_name' in item %}{{ item.campus_name.0 }}, {% endif %}{{ item.repository_name.0 }}</dd>
          {% endif %}

          {% if 'collection_name' in item %}
          <dt class="meta-inline__type">Collection</dt>
          <dd class="meta-inline__defin">{{ item.collection_name.0 }}</dd>
          {% endif %}
        </dl>
      </div>
    </div>
  </div>
{% endfor %}
</div>

calisphere/templates/calisphere/reportCollectionFacetValue.html
{% extends "calisphere/facetValues.html" %}
{% load calisphere-extras %}
{% load static %}
{% load humanize %}

{% block breadcrumbs %}{% endblock %}

{% block pageTitle %}
  <nav class="breadcrumb--style1" aria-label="breadcrumb navigation">
    <ul>
      <li>
        <a href="{% url 'calisphere:collectionsDirectory' %}">Collections</a>
      </li>
      <li>
        items from <a href="{% url 'calisphere:collectionView' collection_id %}">{{ collection.name }}</a>
        with the same {{ facet }}
      </li>
    </ul>
  </nav>
  <h1 id="js-collection" data-collection="{{ collection_id }}" data-referralName="{{ facet_value }}">
    {{ facet_value }}
  </h1>
{% endblock %}

{% block additionalInfo %}

<div class="collection-intro" data-ga-dim1="{{ collection.local_id }}{{ collection.slug }}">
  <div class="col-md-3">
    <div class="collection-intro__institution">
      <h2 class="collection-intro__institution-heading">Owning Institution{{ collection.repository|pluralize }}:
        {% for repository in collection.repository %}
          {% if 'campus' in repository and repository.campus.0.name %}
            <a
              href="{% url 'calisphere:campusCollections' repository.campus.0.slug %}"
              class="collection-intro__institution-heading-link"
            >{{ repository.campus.0.name }}</a>,
          {% endif %}
          <a
            href="{% url 'calisphere:repositoryCollections' repository.resource_id %}"
            class="collection-intro__institution-heading-link"
            data-ga-code="{{ repository.google_analytics_tracking_code }}"
            data-ga-dim2="{%if 'campus' in repository and repository.campus.0.name %}{{ repository.campus.0.slug }}-{% endif %}{{ repository.slug }}"
          >
            {{ repository.name }}
          </a>
          {% if forloop.counter < collection.repository|length %} and {% endif %}
        {% endfor %}
      </h2>
    </div>
  </div>

  <div class="col-md-9">
    <div class="collection-intro__about">
      {% if 'description' in collection %}
      <h3 class="collection-intro__about-heading">About this Collection</h3>
        <span class="collection-intro__about-description">
          {{ collection.description|urlize }}
        </span>
      {% endif %}
      {% if collection.url_local|length > 0 %}
        <a class="collection-intro__about-link" href="{{ collection.url_local }}" target="_blank">View this collection on the contributor's website.</a><br/>
      {% endif %}
      {% if collection.url_oac|length > 0 %}
        <a class="collection-intro__about-link" href="{{ collection.url_oac }}" target="_blank">View collection guide.</a>
      {% endif %}
      <label for="{{ collection_id }}" aria-hidden="true" class="display-none">Current Collection ID</label>
      <input id="{{ collection_id }}" class="facet js-facet facet-collection_data display-none" form="js-facet" type="checkbox" name="collection_data" value="{{ collection_id }}" checked aria-hidden="true">

    </div>
  </div>

</div>

{% endblock %}

{% block sidebar %}
<form id="js-facet" action="{{ form_action }}" method="get">
{% block refineSearch %}
<div class="row">
  <div class="col-sm-6 col-md-12">
      <a class="btn btn-default button__back-to-institution" href="{% url 'calisphere:collectionView' collection_id %}">
        <span class="fa fa-angle-left fa-lg fa-fw"></span>
        Go to Collection Page
      </a>
  </div>

</div>
 {% endblock %}
 </form>
{% endblock %}

{% block objectsFound %}
{{ numFound|intcomma }} item{{ numFound|pluralize }} in this collection have a
  <em>{{ facet }}</em> of
  »{{ facet_value }}«</b>

{% endblock %}

{% block relatedCollections %}
{% endblock %}