calisphere/urls.py
from django.urls import re_path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.conf import settings
from calisphere.home import HomeView
from . import views
from . import collection_views
from . import institution_views

app_name = 'calisphere'

urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
    re_path(r'^select-index/(?P<index>.*)/', views.select_index, name='select_index'),
    re_path(r'^search/$', views.search, name='search'),
    re_path(r'^item/(?P<item_id>.*)/$', views.item_view, name='itemView'),
    re_path(r'^collections/$',
        collection_views.collections_directory,
        name='collectionsDirectory'),
    re_path(r'^collections/(?P<collection_letter>[a-zA-Z]{1})/$',
        collection_views.collections_az,
        name='collectionsAZ'),
    re_path(r'^collections/(?P<collection_letter>num)/$',
        collection_views.collections_az,
        name='collectionsAZ'),
    re_path(r'^collections/(?P<collection_id>\d*)/$',
        collection_views.collection_search,
        name='collectionView'),
    re_path(r'^collections/(?P<collection_id>\d*)/reports/(?P<facet>[^/].*)/(?P<facet_value>.*)/$',
        views.report_collection_facet_value,
        name='reportCollectionFacetValue'),
    re_path(r'^collections/(?P<collection_id>\d*)/reports/(?P<facet>.*)/$',
        views.report_collection_facet,
        name='reportCollectionFacet'),
    re_path(r'^collections/(?P<collection_id>\d*)/(?P<cluster>[^/].*)/(?P<cluster_value>.*)/$',
        collection_views.collection_facet_value,
        name='collectionFacetValue'),
    re_path(r'^collections/(?P<collection_id>\d*)/(?P<facet>.*)/$',
        collection_views.collection_facet,
        name='collectionFacet'),
    re_path(r'^collections/(?P<collection_id>\d*)/(?P<facet>.*).json$',
        collection_views.collection_facet_json,
        name='collectionFacetJson'),

    # Redirects to new 'exhibitions'
    re_path(r'^collections/themed/$',
        RedirectView.as_view(url='/exhibitions/'),
        name='themedCollections'),
    re_path(r'^collections/cal-cultures/$',
        RedirectView.as_view(url='/cal-cultures/'),
        name='calCultures'),
    re_path(r'^collections/jarda/$',
        RedirectView.as_view(url='/exhibitions/t11/jarda/'),
        name='jarda'),
    re_path(r'^collections/titleSearch/$',
        collection_views.collections_search,
        name='collectionsTitleSearch'),
    re_path(r'^collections/titles.json$',
        collection_views.collections_titles,
        name='collectionsTitleData'),

    re_path(r'^institution/(?P<repository_id>\d*)/$',
        institution_views.repository_collections,
        name='repositoryCollections'),
    re_path(r'^institution/(?P<repository_id>\d*)/collections/$',
        institution_views.repository_collections,
        name='repositoryCollections'),
    re_path(r'^institution/(?P<repository_id>\d*)/items/$',
        institution_views.repository_search,
        name='repositorySearch'),

    re_path(r'^(?P<campus_slug>UC\w{1,2})/$',
        institution_views.campus_collections,
        name='campusCollections'),
    re_path(r'^(?P<campus_slug>UC\w{1,2})/collections/$',
        institution_views.campus_collections,
        name='campusCollections'),
    re_path(r'^(?P<campus_slug>UC\w{1,2})/items/$',
        institution_views.campus_search,
        name='campusSearch'),
    re_path(r'^(?P<campus_slug>UC\w{1,2})/institutions/$',
        institution_views.campus_institutions,
        name='campusInstitutions'),

    re_path(r'^institutions/$', institution_views.campus_directory, name='campusDirectory'),
    re_path(r'^institutions/statewide-partners/$',
        institution_views.statewide_directory,
        name='statewideDirectory'),
    re_path(r'about/$',
        TemplateView.as_view(template_name='calisphere/about.html'),
        name='about'),
    re_path(r'help/$',
        TemplateView.as_view(template_name='calisphere/help.html'),
        name='help'),
    re_path(r'terms/$',
        TemplateView.as_view(template_name='calisphere/termsOfUse.html'),
        name='termsOfUse'),
    re_path(r'privacy/$',
        TemplateView.as_view(template_name='calisphere/privacyStatement.html'),
        name='privacyStatement'),
    re_path(r'outreach/$',
        TemplateView.as_view(template_name='calisphere/outreach.html'),
        name='outreach'),
    re_path(r'contribute/$',
        TemplateView.as_view(template_name='calisphere/contribute.html'),
        name='contribute'),
    re_path(r'jobs/$',
        TemplateView.as_view(template_name='calisphere/jobs.html'),
        name='jobs'),
    re_path(r'overview/$', 
        TemplateView.as_view(template_name='calisphere/overview.html'),
        name='overview'),
    re_path(r'posters/$', views.posters, name='posters'),
    re_path(r'sitemap-(?P<section>.*).xml$', views.sitemap_section),
    re_path(r'sitemap-(?P<section>.*).xml.gz$', views.sitemap_section_zipped),

    # AJAX HELPERS
    re_path(r'^relatedCollections/',
        views.related_collections,
        name='relatedCollections'),
    re_path(r'^relatedExhibitions',
        views.related_exhibitions,
        name='relatedExhibitions'),
    re_path(r'^carousel/', views.item_view_carousel, name='carousel'),
    re_path(r'^contactOwner/', views.contact_owner, name='contactOwner'),
]

if settings.UCLDC_METADATA_SUMMARY:
    urlpatterns.insert(0,
        re_path(r'^collections/(?P<collection_id>\d*)/metadata/$',
            collection_views.collection_metadata,
            name='collectionMetadata'),
    )
    urlpatterns.insert(0,
        re_path(r'^collections/(?P<collection_id>\d*)/browse/$',
            collection_views.collection_browse,
            name='collectionBrowse'),)

calisphere/templates/calisphere/collections/collectionBrowse.html
{% extends "calisphere/2col.html" %}
{% load calisphere-extras %}
{% load static %}
{% load humanize %}

{% block title %}: {{ collection.name }}{% endblock %}
{% block page-metadata %}
{% include "calisphere/microdata.html" with title=collection.name description=collection.description %}
{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block pageTitle %}
  <nav class="breadcrumb--style1" aria-label="breadcrumb navigation">
    <ul>
      <li>
        <a href="{% url 'calisphere:collectionsDirectory' %}">Collections</a>
      </li>
    </ul>
  </nav>

  <h1 id="js-collection" data-collection="{{ collection_id }}" data-referralName="{{ collection.name }}">
    {{ collection.name }}
  </h1>
{% endblock %}

{% block additionalInfo %}
  <div class="collection-intro" data-ga-dim1="{{ collection.local_id }}{{ collection.slug }}">
    <div class="col-md-3">
      <div class="collection-intro__institution">
        <h2 class="collection-intro__institution-heading">Owning Institution{{ collection.repository|pluralize }}:
          {% for repository in collection.repository %}
            {% if 'campus' in repository and repository.campus|length > 0 %}
              {% if repository.campus.0.name %}
                <a
                  href="{% url 'calisphere:campusCollections' repository.campus.0.slug %}"
                  class="collection-intro__institution-heading-link"
                >{{ repository.campus.0.name }}</a>,
              {% endif %}
            {% endif %}
            <a
              href="{% url 'calisphere:repositoryCollections' repository.resource_id %}"
              class="collection-intro__institution-heading-link"
              data-ga-code="{{ repository.google_analytics_tracking_code }}"
              data-ga-dim2="{%if 'campus' in repository and repository.campus.0.name %}{{ repository.campus.0.slug }}-{% endif %}{{ repository.slug }}"
            >
              {{ repository.name }}
            </a>
            {% if forloop.counter < collection.repository|length %} and {% endif %}
          {% endfor %}
        </h2>
      </div>
    </div>

    <div class="col-md-9">
      <div class="collection-intro__about">
        {% if 'description' in collection %}
        <h3 class="collection-intro__about-heading">About this Collection</h3>
          <span class="collection-intro__about-description">
            {{ collection.description|urlize }}
          </span>
        {% endif %}
        {% if collection.url_local|length > 0 %}
          <a class="collection-intro__about-link" href="{{ collection.url_local }}" target="_blank">View this collection on the contributor's website.</a><br/>
        {% endif %}
        {% if collection.url_oac|length > 0 %}
          <a class="collection-intro__about-link" href="{{ collection.url_oac }}" target="_blank">View collection guide.</a>
        {% endif %}
        <label for="{{ collection_id }}" aria-hidden="true" class="display-none">Current Collection ID</label>
        <input id="{{ collection_id }}" class="facet js-facet facet-collection_data display-none" form="js-facet" type="checkbox" name="collection_data" value="{{ collection_id }}" checked aria-hidden="true">

      </div>
    </div>
  </div>
{% endblock %}

{% block sidebar %}
  <div class="row">
    <div class="col-sm-6 col-md-12">
      <div class="button__institution-tabs-container">
        <a class="button__institution-tab-collections--selected"
        href="{% url 'calisphere:collectionBrowse' collection_id %}">
          Browse collection
        </a>
        <a class="button__institution-tab-search" href="{% url 'calisphere:collectionView' collection_id %}">
          Search this collection
        </a>
      </div>
    </div>
    <div class="col-sm-6 col-md-12">
      {% if collection.repository|length > 1 %}
      {% for repository in collection.repository %}
        <a class="btn btn-default button__back-to-institution" href="{% url 'calisphere:repositoryCollections' repository.resource_id %}">
          <span class="fa fa-angle-left fa-lg fa-fw"></span>
          Go to {{ repository.name }} Page
        </a>
      {% endfor %}
      {% else %}
      {% with collection.repository.0 as repository %}
        <a class="btn btn-default button__back-to-institution" href="{% url 'calisphere:repositoryCollections' repository.resource_id %}">
          <span class="fa fa-angle-left fa-lg fa-fw"></span>
          Go to Institution Page
        </a>
      {% endwith %}
      {% endif %}
    </div>
    <div class="col-sm-6 col-md-12">
      {% include "calisphere/collections/collectionSnapshot.html" %}
    </div>
  </div>
{% endblock %}

{% block mainContent %}
  <h2 class="text__institution-heading2">Browse {{collection.name}}</h2>

  {% for cluster in clusters %}
  <div class="row explore-clusters">
    <div class="col-md-5 cluster-listing">
      <h3>{{ cluster.facet_field.display|title }}{% if cluster.facet_field.display != 'rights' %}s{% endif %} in this Collection</h3>
      {% if cluster.unique >= 3 %}
      <h4 class="sr-only">Three Sample {{ cluster.facet_field.display|title }}{% if cluster.facet_field.display != 'rights' %}s{% endif %}</h4>
      {% else %}
      <h4 class="sr-only">{{ cluster.unique|apnumber|title }} {{ cluster.facet_field.display|title }}{% if cluster.facet_field.display != 'rights' %}{{ cluster.unique|pluralize }}{% endif %}</h4>
      {% endif %}
      <ol>
        {% for value in cluster.values %}
          {% if forloop.counter0 < 3 %}
          <li>
            {% if forloop.counter0 == 0 %}<strong>{% endif %}
              <a href="{{ value.uri }}?view_format=list">{{ value.label }} ({{ value.count|intcomma }} items)</a>
            {% if forloop.counter0 == 0 %}</strong>{% endif %}
          </li>
          {% endif %}
        {% endfor %}
      </ol>

      <a href="{{ form_action }}{{ cluster.facet_field.facet }}/" class="btn-default btn btn button__cluster-values">See all {{ cluster.unique|intcomma }} {{ cluster.facet_field.display|lower }}{% if cluster.facet_field.display != 'rights' %}{{ cluster.unique|pluralize }}{% endif %}</a>

      {% if cluster.unique > 3 %}
      <h4 class="sr-only">Search for a {{cluster.facet_field.display}}</h4>
      <form class="clustersearch__form-{{cluster.facet_field.facet}}" role="search" onsubmit="false()">
        <label for="clustersearch__field-{{cluster.facet_field.facet}}" class="sr-only">
          Search for a {{cluster.facet_field.display}}
        </label>
        <div class="input-group">
          <input id="clustersearch__field-{{cluster.facet_field.facet}}" type="search" placeholder="Search for a {{cluster.facet_field.display}}" class="form-control search__cluster-values">
            <span class="input-group-btn">
              <button class="btn btn-default global-search__button" type="submit" aria-label="search"><span class="fa fa-search"></span>
              </button>
            </span>
          </input>
        </div>
      </form>
      {% endif %}

    </div>
    <a href="{{cluster.values.0.uri}}">
    <div class="col-md-7">
      <div class="browse-cluster-thumbnail__container">
        {% for thumb in cluster.thumbnails %}
          {% if forloop.counter0 == 1 %}
          <div class="browse-cluster-thumbnail__container2">
          {% endif %}
          {% if forloop.counter0 == 2 %}
          <div class="browse-cluster-thumbnail__container3">
          {% endif %}

          <div class="browse-cluster-thumbnail__{{forloop.counter0}}"
            style="background-image: url({{ thumbnailUrl }}crop/210x210/{{ thumb.reference_image_md5 }})">

              {% if 'reference_image_md5' in thumb %}
                {% if thumb.type.0|lower == "moving image" %}
                <div class="thumbnail__overlay-icon fa-play-circle-o"></div>
                {% elif thumb.type.0|lower == "sound"%}
                <div class="thumbnail__overlay-icon fa-volume-up"></div>
                {# elif thumb.type.0|lower == "text" #}
                <!-- <div class="thumbnail__overlay-icon fa-file-text-o"></div> -->
                {% elif thumb.type.0|lower == "dataset" %}
                <div class="thumbnail__overlay-icon fa-bar-chart"></div>
                {% endif %}

              {% else %}
                {% if thumb.type.0|lower == "moving image" %}
                <div class="thumbnail__tile-icon fa-play-circle-o"></div>
                {% elif thumb.type.0|lower == "sound"%}
                <div class="thumbnail__tile-icon fa-volume-up"></div>
                {% elif thumb.type.0|lower == "text"%}
                <div class="thumbnail__tile-icon fa-file-text-o"></div>
                {% elif thumb.type.0|lower == "dataset" %}
                <div class="thumbnail__tile-icon fa-bar-chart"></div>
                {% elif thumb.type.0|lower == "image" %}
                <div class="thumbnail__tile-icon fa-picture-o"></div>
                {% else %}
                <div class="thumbnail__tile-icon fa-file"></div>
                {% endif %}
              {% endif %}

          </div>
        {% endfor %}
          {% if cluster.thumbnails|length == 2 %}
          <div class="browse-cluster-thumbnail__container3">
          {% endif %}
          <div class="browse-cluster-thumbnail__{{cluster.thumbnails|length}} browse-cluster-thumbnail__description">
            View all items with {{ cluster.facet_field.display }} "{{cluster.values.0.label|truncatewords:4}}" in this collection.
          </div>
        {% if cluster.thumbnails|length >= 2 %}
        </div></div>
        {% endif %}
      </div>
    </div>
    </a>
  </div>
  {% endfor %}

  <script>
  var cluster_fields = [];
  {% for cluster in clusters %}
  cluster_fields.push('{{ cluster.facet_field.facet }}');
  {% endfor %}

  var clusters = {
    'collection_id': {{collection_id}},
    'clusters': cluster_fields
  };
  </script>
{% endblock %}

calisphere/templates/calisphere/collections/collectionFacetValue.html
{% extends "calisphere/searchResults.html" %}
{% load calisphere-extras %}
{% load static %}
{% load humanize %}

{% block breadcrumbs %}{% endblock %}

{% block pageTitle %}
  <nav class="breadcrumb--style1" aria-label="breadcrumb navigation">
    <ul>
      <li>
        <a href="{% url 'calisphere:collectionsDirectory' %}">Collections</a>
      </li>
      <li>
        <a href="{% url 'calisphere:collectionView' collection_id %}">{{ collection.name }}</a>
      <li>
        Items with {{ cluster }} "{{ cluster_value }}"
      </li>
    </ul>
  </nav>
  <h1 id="js-collection" data-collection="{{ collection_id }}" data-referralName="{{ cluster_value }}">
    Items with {{ cluster }} "{{ cluster_value }}"
  </h1>
{% endblock %}

{% block additionalInfo %}

<div class="collection-intro" data-ga-dim1="{{ collection.local_id }}{{ collection.slug }}">
  <div class="col-md-3">
    <div class="collection-intro__institution">
      <h2 class="collection-intro__institution-heading">Collection:
        <a class="collection-intro__instition-heading-link" 
           href="{% url 'calisphere:collectionView' collection_id %}" >
            {{ collection.name }}
          </a>
      </h2><br/>

      <h2 class="collection-intro__institution-heading">Owning Institution{{ collection.repository|pluralize }}:
        {% for repository in collection.repository %}
          {% if 'campus' in repository and repository.campus.0.name %}
            <a
              href="{% url 'calisphere:campusCollections' repository.campus.0.slug %}"
              class="collection-intro__institution-heading-link"
            >{{ repository.campus.0.name }}</a>,
          {% endif %}
          <a
            href="{% url 'calisphere:repositoryCollections' repository.resource_id %}"
            class="collection-intro__institution-heading-link"
            data-ga-code="{{ repository.google_analytics_tracking_code }}"
            data-ga-dim2="{%if 'campus' in repository and repository.campus.0.name %}{{ repository.campus.0.slug }}-{% endif %}{{ repository.slug }}"
          >
            {{ repository.name }}
          </a>
          {% if forloop.counter < collection.repository|length %} and {% endif %}
        {% endfor %}
      </h2>
    </div>
  </div>

  <div class="col-md-9">
    <div class="collection-intro__about">
      {% if 'description' in collection %}
      <h3 class="collection-intro__about-heading">About this Collection</h3>
        <span class="collection-intro__about-description">
          {{ collection.description|urlize }}
        </span>
      {% endif %}
      {% if collection.url_local|length > 0 %}
        <a class="collection-intro__about-link" href="{{ collection.url_local }}" target="_blank">View this collection on the contributor's website.</a><br/>
      {% endif %}
      {% if collection.url_oac|length > 0 %}
        <a class="collection-intro__about-link" href="{{ collection.url_oac }}" target="_blank">View collection guide.</a>
      {% endif %}
      <label for="{{ collection_id }}" aria-hidden="true" class="display-none">Current Collection ID</label>
      <input id="{{ collection_id }}" class="facet js-facet facet-collection_data display-none" form="js-facet" type="checkbox" name="collection_data" value="{{ collection_id }}" checked aria-hidden="true">

    </div>
  </div>

</div>

{% endblock %}

{% block refineSearch %}
<div class="row">
  <div class="col-sm-6 col-md-12">
    <div class="button__institution-tabs-container">
      <a class="button__institution-tab-collections"
      href="{% url 'calisphere:collectionBrowse' collection_id %}">
        Browse collection
      </a>
      <a class="button__institution-tab-search" href="{% url 'calisphere:collectionView' collection_id %}">
        Search this collection
      </a>
    </div>
  </div>
  <div class="col-sm-6 col-md-12">
      <a class="btn btn-default button__back-to-institution" href="{% url 'calisphere:collectionFacet' collection_id cluster %}">
        <span class="fa fa-angle-left fa-lg fa-fw"></span>
        View {{ cluster|title }}{% if cluster != 'rights'%}s{% endif %} List
      </a>
  </div>

  <div class="col-sm-6 col-md-12">
    <!-- Begin Search Collection Field -->

    <div class="search-collection">
      <!-- <label for="search-collection__field" class="search-collection__label">Search within collection</label> -->
      <div class="input-group">
        <input id="search-collection__field" type="search" name="rq" class="form-control search-collection__field" form="js-facet">
        <span class="input-group-btn">
          <button class="btn btn-default search-collection__button" type="submit" form="js-facet">Search cluster
          </button>
        </span>
      </div>
    </div>

    <!-- End Search Collection Field -->
  </div>

</div>
{% endblock %}


{% block objectsFound %}
{{ numFound|intcomma }} item{{ numFound|pluralize }} from this collection all share the same {{cluster}}: {{cluster_value}}

<!-- <p>These items from the <a href="{% url 'calisphere:collectionView' collection_id %}">{{ collection.name }}</a> all share the same {{ cluster }}: {{ cluster_value }}.</p> -->
{% endblock %}

{% block relatedCollections %}
{% endblock %}

calisphere/templates/calisphere/collections/collectionMetadata.html
{% extends "calisphere/base.html" %}
{% load calisphere-extras %}
{% load static %}
{% load humanize %}

{% block content %}

<h2 class="collection-intro__institution-heading">Collection:
	<a href="{% url 'calisphere:collectionView' collection_id %}">
		{{ collection.name }}
	</a>
</h2>
<h2 class="collection-intro__institution-heading">Owning Institution{{ collection.repository|pluralize }}:
{% for repository in collection.repository %}
  {% if 'campus' in repository and repository.campus.0.name %}
    <a
      href="{% url 'calisphere:campusCollections' repository.campus.0.slug %}"
      class="collection-intro__institution-heading-link"
    >{{ repository.campus.0.name }}</a>,
  {% endif %}
  <a
    href="{% url 'calisphere:repositoryCollections' repository.resource_id %}"
    class="collection-intro__institution-heading-link"
  >
    {{ repository.name }}
  </a>
{% endfor %}
</h2>

<h3>Metadata Summary</h3>
{{ summary_data.item_count|intcomma }} records in this collection

<table class="metadata-summary" border="1">
  <tr>
    <th>field</th>
    <th>% records <br/> with field</th>
    <th>% unique values <br/> in field</th>
  </tr>
  {% for facet, info in summary_data.items %}
    {% if facet != 'item_count' and facet != 'collection_url' %}
  <tr>
      {% if info.uniq_percent == None or facet == 'description' or facet == 'transcription' %}
    <td>{{ facet }}</td>
      {% else %}
    <td><a href="{% url 'calisphere:reportCollectionFacet' collection_id facet %}">{{ facet }}</a></td>
      {% endif %}
    <td>{{ info.percent }}</td>
      {% if facet != 'rights_uri' and facet != 'transcription' %}
    <td>{{ info.uniq_percent|default_if_none:"" }}</td>
      {% endif %}
  </tr>
    {% endif %}
  {% endfor %}
</table>

{% endblock %}

calisphere/templates/calisphere/collections/collectionView.html
{% extends "calisphere/searchResults.html" %}
{% load calisphere-extras %}
{% load static %}
{% load humanize %}

{% block breadcrumbs %}{% endblock %}

{% block title %}: {{ collection.name }}{% endblock %}
{% block page-metadata %}
{% include "calisphere/microdata.html" with title=collection.name description=collection.description %}
{% endblock %}

{% block pageTitle %}
  <nav class="breadcrumb--style1" aria-label="breadcrumb navigation">
    <ul>
      <li>
        <a href="{% url 'calisphere:collectionsDirectory' %}">Collections</a>
      </li>
    </ul>
  </nav>

  <h1 id="js-collection" data-collection="{{ collection_id }}" data-referralName="{{ collection.name }}">
    {{ collection.name }}
  </h1>
{% endblock %}

{% block additionalInfo %}

<div class="collection-intro" data-ga-dim1="{{ collection.local_id }}{{ collection.slug }}">
  <div class="col-md-3">
    <div class="collection-intro__institution">
      <h2 class="collection-intro__institution-heading">Owning Institution{{ collection.repository|pluralize }}:
        {% for repository in collection.repository %}
          {% if 'campus' in repository and repository.campus.0.name %}
            <a
              href="{% url 'calisphere:campusCollections' repository.campus.0.slug %}"
              class="collection-intro__institution-heading-link"
            >{{ repository.campus.0.name }}</a>,
          {% endif %}
          <a
            href="{% url 'calisphere:repositoryCollections' repository.resource_id %}"
            class="collection-intro__institution-heading-link"
            data-ga-code="{{ repository.google_analytics_tracking_code }}"
            data-ga-dim2="{%if 'campus' in repository and repository.campus.0.name %}{{ repository.campus.0.slug }}-{% endif %}{{ repository.slug }}"
          >
            {{ repository.name }}
          </a>
          {% if forloop.counter < collection.repository|length %} and {% endif %}
        {% endfor %}
      </h2>
    </div>
  </div>

  <div class="col-md-9">
    <div class="collection-intro__about">
      {% if 'description' in collection %}
      <h3 class="collection-intro__about-heading">About this Collection</h3>
        <span class="collection-intro__about-description">
          {{ collection.description|linebreaksbr|urlize }}
        </span>
      {% endif %}
      {% if collection.url_local|length > 0 %}
        <span class="collection-intro__about-link">View this collection on the <a href="{{ collection.url_local }}" target="_blank">contributor's website</a>.</span><br/>
      {% endif %}
      {% if collection.url_oac|length > 0 %}
        <span class="collection-intro__about-link">View <a href="{{ collection.url_oac }}" target="_blank">collection guide</a>.</span><br/>
      {% endif %}
        <p>View our <a href="/overview/">statement on digital primary resources and historical description</a>.</p>

      <label for="{{ collection_id }}" aria-hidden="true" class="display-none">Current Collection ID</label>
      <input id="{{ collection_id }}" class="facet js-facet facet-collection_data display-none" form="js-facet" type="checkbox" name="collection_data" value="{{ collection_id }}" checked aria-hidden="true">

    </div>
  </div>

</div>

{% endblock %}

{% block refineSearch %}
<div class="row">

  {% if browse %}
  <div class="col-sm-6 col-md-12">
    <div class="button__institution-tabs-container">
      <a class="button__institution-tab-collections"
      href="{% url 'calisphere:collectionBrowse' collection_id %}">
        Browse collection
      </a>
      <a class="button__institution-tab-search--selected" href="{% url 'calisphere:collectionView' collection_id %}">
        Search this collection
      </a>
    </div>
  </div>
  {% endif %}

  <div class="col-sm-6 col-md-12">
    {% if collection.repository|length > 1 %}
    {% for repository in collection.repository %}
      <a class="btn btn-default button__back-to-institution" href="{% url 'calisphere:repositoryCollections' repository.resource_id %}">
        <span class="fa fa-angle-left fa-lg fa-fw"></span>
        Go to {{ repository.name }} Page
      </a>
    {% endfor %}
    {% else %}
    {% with collection.repository.0 as repository %}
      <a class="btn btn-default button__back-to-institution" href="{% url 'calisphere:repositoryCollections' repository.resource_id %}">
        <span class="fa fa-angle-left fa-lg fa-fw"></span>
        Go to Institution Page
      </a>
    {% endwith %}
    {% endif %}
  </div>

  <div class="col-sm-6 col-md-12">
    <!-- Begin Search Collection Field -->

    <div class="search-collection">
      <label for="search-collection__field" class="search-collection__label">Search within collection</label>
      <div class="input-group">
        <input id="search-collection__field" type="search" name="rq" class="form-control search-collection__field" form="js-facet">
        <span class="input-group-btn">
          <button class="btn btn-default search-collection__button" type="submit" form="js-facet">Refine
          </button>
        </span>
      </div>
    </div>

    <!-- End Search Collection Field -->
  </div>

</div>
{% endblock %}

{% block objectsFound %}
{{ numFound|intcomma }} item{{ numFound|pluralize }} found in this collection {% if numFound != totalNumItems %} of <a class="js-clear-filters">{{ totalNumItems }} items</a>{% endif %}
{% endblock %}

{% block relatedCollections %}
{% endblock %}

calisphere/templates/calisphere/collections/collectionsDirectory.html
{% extends "calisphere/base.html" %}
{% load calisphere-extras %}
{% load static %}

{% block page-metadata %}
{% include "calisphere/microdata.html" with title='Collections Directory' %}
{% endblock %}

{% block content %}

  {% include "calisphere/collections/collectionsHeader.html" %}

  {% block collectionContent %}
  {% endblock %}

{% endblock %}